---
- name: run apt-get update
  apt:
    update_cache: yes

- name: run apt-get upgrade
  apt:
    upgrade: dist

- name: update sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?Port 22'
    line: 'Port 6522'
    backup: yes
  notify:
    - restart sshd

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: copy config file to /etc/logrotate.d
  copy:
    src: "nginx.conf"
    dest: "/etc/logrotate.d/nginx.conf"
    owner: root
    group: root
    mode: 0644

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    "{{ packages }}"

- name: create tmp folder
  file:
    path: /tmp/fefiles
    state: directory

- name: download zip from S3
  amazon.aws.aws_s3:
    bucket: skillup-s3-aa.achico-001
    mode: get
    object: frontend.zip
    dest: "/tmp/fefiles/frontend.zip"

- name: extract zip file to /var/www/html/
  unarchive:
    src: "/tmp/fefiles/frontend.zip"
    dest: "/var/www/html"

- name: set private ip address in index.html
  replace:
    path: /var/www/html/index.html
    regexp: 'pri_ip_address(.*)'
    replace: "{{ pri_ip_address }}"
  notify: 
    - restart apache2

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: delete tmp folder
  file:
    path: /tmp/fefiles
    state: absent

- name: create users
  user:
    name: "{{ item }}"
  with_items:
    "{{ users }}"

- name: delete user carrot
  user:
    name: carrot
    state: absent
    remove: yes

- name: set permission to 0600
  file:
    path: /var/log/syslog
    mode: '0600'